### ISSUE TITLE
Página de inicio

### ISSUE THREAD

**Issue by jdfuturistic** [AndreiRico/AndromedaAplicacionWeb#12]
Crear un home que contenga una bienvenida, muestre planes, servicios y productos, que añada botón en el Nav de Iniciar Sesión y Registrese, que tenga botones que nos arrastre a las secciones y que tenga un botón extra que nos lleve a la página de Acerca de

**Comment by jdfuturistic** [comment]
Añadirle btn de Acerca de en el Nav para ver la Misión y Visión

**Comment by DeliaOsorio** [comment]
El botón **REGISTRARSE** que está en el banner no está redirigiendo al formulario de REGISTRO.

**Comment by AndreiRico** [comment]
![Image](https://user-images.githubusercontent.com/111542909/203612972-b997bf70-23b2-4f7b-b1e3-4ecf51166681.png)



![Image](https://user-images.githubusercontent.com/111542909/203612995-00352071-923a-426f-ad0e-277061f17891.png)
