### ISSUE TITLE
CRUD prospecto

### ISSUE THREAD

**Issue by jdfuturistic** [AndreiRico/AndromedaAplicacionWeb#17]
Crear CRUD para Prospectos en Administración

**Comment by jdfuturistic** [comment]
**Listado de Prospectos (vista para el asesor)**

![Image](https://user-images.githubusercontent.com/107774756/203180399-5c9a48ad-a93a-4cf2-a788-b256da67d020.png)

**Crear Prospecto (vista para el interesado)**

![Image](https://user-images.githubusercontent.com/107774756/203181465-54e258ef-82e0-4ca0-b567-d293a69352d1.png)

**Actualizar Prospecto (vista para el asesor)**

![Image](https://user-images.githubusercontent.com/107774756/203180972-64dff941-02da-4ea1-9264-66e724c282ff.png)

**Mensaje de confirmación de la actualización**

![Image](https://user-images.githubusercontent.com/107774756/203181124-471b1c1e-824e-4b41-9c0b-fb5d7e226a5f.png)

**Eliminar Prospecto (vista para el asesor)**

![Image](https://user-images.githubusercontent.com/107774756/203181779-9bd1244b-899e-4ece-bf16-11bb63b953c1.png)

**Mensaje de confirmación de eliminación**

![Image](https://user-images.githubusercontent.com/107774756/203182138-a0da1bc0-3c44-497d-afb3-cb5f7f038f6e.png)

**Comment by jdfuturistic** [comment]
Voy a intentar añadirle el redireccionamiento, el botón "Más Información" al formulario de Contáctenme

**Comment by DeliaOsorio** [comment]
El botón **MÁS INFORMACIÓN** del footer ya redirige hacia el formulario de Contáctenos
