### ISSUE TITLE
CRUD mascotas (Asesor-Administrador)

### ISSUE THREAD

**Issue by jdfuturistic** [AndreiRico/AndromedaAplicacionWeb#18]
Crear un CRUD de Mascotas para que tanto el Administrador como el Asesor tengan Acceso para Aceptar la Mascota a Afiliar

**Comment by jdfuturistic** [comment]
**Listado completo de mascotas, incluye el nombre del plan y el nombre del propietario**

![Image](https://user-images.githubusercontent.com/107774756/203368860-10536cfd-ff50-4a6f-924d-5af5b37f48ad.png)

**Formulario Crear mascota**

![Image](https://user-images.githubusercontent.com/107774756/203588460-c7cffe50-cce9-4073-bfc4-f8a6890626f8.png)

**Formulario Actualizar Mascota. El asesor puede cambiar el estado**

![Image](https://user-images.githubusercontent.com/107774756/203588915-446c952b-46aa-4ae3-9cc6-aab4238efe52.png)

**Eliminar mascota**

![Image](https://user-images.githubusercontent.com/107774756/203589329-07ab76b0-267c-43d2-b2bb-7a5ba8a3dc56.png)

**Comment by DeliaOsorio** [comment]
.

**Comment by DeliaOsorio** [comment]
.
