### ISSUE TITLE
CRUD mascotas (Cliente)

### ISSUE THREAD

**Issue by jdfuturistic** [AndreiRico/AndromedaAplicacionWeb#3]
Crear los métodos Crear y Listar para Mascotas

**Comment by DeliaOsorio** [comment]
Listado de las mascotas de un usuario:

![Image](https://user-images.githubusercontent.com/107774756/203663505-0abeb3c7-41ad-4879-aefd-184c59557533.png)

Formulario para crear mascota:

![Image](https://user-images.githubusercontent.com/107774756/203663676-5733b16f-96a8-4b65-bc7c-6817259570b4.png)

**Comment by DeliaOsorio** [comment]
Culminado
